version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_marketplace_two_developers
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: 'bitnami/postgresql:latest'
    container_name: marketplace_db
    ports:
      - "5432:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_DB=laravelmarketplace
      - POSTGRES_USER=twodevelopers
      - POSTGRES_PASSWORD=c_z7@Oc*@65s
    volumes:
      - pgdata:/bitnami/postgresql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
